--init spms_area--
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('10', '1', '2014-09-18 15:57:00', NULL, '1', '110106', '石景山区', '0,1,2,', NULL, NULL, '4', NULL, NULL, '2', '11');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('11', '1', '2014-10-08 18:25:00', NULL, '2', '110200', '北京配电区', '0,1,', NULL, NULL, '2', NULL, NULL, NULL, '2');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('12', '1', '2014-10-08 18:26:00', NULL, '2', '110201', '北配区一', '0,1,11,', NULL, NULL, '4', NULL, NULL, '11', '3');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('13', '1', '2014-10-08 18:28:00', NULL, '2', '110202', '北配区二', '0,1,11,', NULL, NULL, '4', NULL, NULL, '11', '4');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('14', '1', '2014-10-08 18:28:00', NULL, '2', '110203', '北配区三', '0,1,11,', NULL, NULL, '4', NULL, NULL, '11', '5');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('15', '1', '2014-10-08 18:29:00', NULL, '2', '110204', '北配区四', '0,1,11,', NULL, NULL, '4', NULL, NULL, '11', '6');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('16', '1', '2014-10-08 18:29:00', NULL, '2', '110205', '北配区五', '0,1,11,', NULL, NULL, '4', NULL, NULL, '11', '7');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('17', '1', '2014-10-08 18:29:00', NULL, '2', '110206', '北配区六', '0,1,11,', NULL, NULL, '4', NULL, NULL, '11', '8');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('18', '1', '2014-10-08 18:29:00', NULL, '2', '110207', '北配区七', '0,1,11,', NULL, NULL, '4', NULL, NULL, '11', '9');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('19', '1', '2014-10-08 18:30:00', NULL, '2', '110208', '北配区八', '0,1,11,', NULL, NULL, '4', NULL, NULL, '11', '10');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('2', '1', '2013-05-27 08:00:00', NULL, '1', '110000', '北京市', '0,1,', NULL, NULL, '2', NULL, NULL, NULL, '1');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('3', '1', '2013-05-27 08:00:00', NULL, '1', '110101', '海淀区', '0,1,2,', NULL, NULL, '4', NULL, NULL, '2', '12');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('4', '1', '2013-05-27 08:00:00', NULL, '1', '110102', '西城区', '0,1,2,', NULL, NULL, '4', NULL, NULL, '2', '13');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('5', '1', '2013-05-27 08:00:00', NULL, '1', '110103', '朝阳区', '0,1,2,', NULL, NULL, '4', NULL, NULL, '2', '14');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('5eca06f1508a40e7b8f17b3bbe39df24', '1', '2014-11-19 10:53:00', NULL, '1', '1111', '三次测试', '0,1,2,3,', NULL, NULL, '1', NULL, NULL, '3', '15');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('6', '1', '2013-05-27 08:00:00', NULL, '1', '110104', '丰台区', '0,1,2,', NULL, NULL, '4', NULL, NULL, '2', '16');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('7', '1', '2013-05-27 08:00:00', NULL, '1', '110105', '东城区', '0,1,2,', NULL, NULL, '4', NULL, NULL, '2', '17');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('733d8928a42b47afadbe6ee726c84b63', '1', '2014-11-19 10:53:00', NULL, '1', '', '再次测试', '0,1,2,', NULL, NULL, '4', NULL, NULL, '2', '18');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('7996af68d0cd4185945e08030c5ffa0a', '1', '2014-11-18 13:55:00', NULL, '1', '', '梵蒂冈', '0,1,2,80efb50a2ec24c6aab13381e4d39b502,', NULL, NULL, '1', NULL, NULL, '80efb50a2ec24c6aab13381e4d39b502', '19');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('8', '1', '2014-10-08 18:18:00', NULL, '1', '110108', '房山区', '0,1,2,', NULL, NULL, '4', NULL, NULL, '2', '20');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('80efb50a2ec24c6aab13381e4d39b502', '1', '2014-11-18 11:32:00', NULL, '1', '', 'apk111', '0,1,2,', NULL, NULL, '1', NULL, NULL, '2', '21');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('9', '1', '2014-10-08 18:18:00', NULL, '1', '110107', '门头沟区', '0,1,2,', NULL, NULL, '4', NULL, NULL, '2', '22');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('de99c228fc57463f9bf95ca80f224ce5', '1', '2014-11-04 15:01:00', NULL, '1', '111111', 'sss', '0,1,2,', NULL, NULL, '1', NULL, NULL, '2', '23');
INSERT INTO `spms_otonew`.`spms_area` (`id`, `version`, `createDate`, `lastModifyDate`, `classification`, `code`, `name`, `parentIds`, `policy`, `remarks`, `type`, `createUser_id`, `lastModifyUser_id`, `parent_id`, `sort`) VALUES ('f778b661693347189a51a72e6ff8ebfe', '1', '2014-11-19 10:51:00', NULL, '1', '17799', '测试地区', '0,1,2,', NULL, NULL, '3', NULL, NULL, '2', '24');


-- init spms_product_type--
INSERT INTO `spms_otonew`.`spms_product_type` (`id`, `version`, `createDate`, `lastModifyDate`, `chuangGanCount`, `configurationInformation`, `countRmb`, `deleteStauts`, `describes`, `electrovalenceRmb`, `indexRmb`, `kongTiaoCount`, `lianDong`, `muluId`, `names`, `refundable`, `rmbType`, `statuss`, `stops`, `upgradeable`, `validPeriod`, `zhiLengMax`, `zhiLengMix`, `zhiReMax`, `zhiReMix`, `createUser_id`, `lastModifyUser_id`, `area_id`, `sensorEnabled`, `status`) VALUES ('4028e49b4b538e7e014b5393bc140000', '0', '2015-02-04 15:52:45', '2015-02-04 15:52:45', '3', '1', '4000', NULL, '虚拟空调服务', '3000', '2000', '3', '0', '1', '智能空调服务1(test)', NULL, '1', NULL, NULL, NULL, '3', '22', '18', '32', '25', '1', '1', '2', NULL, '2');
INSERT INTO `spms_otonew`.`spms_product_type` (`id`, `version`, `createDate`, `lastModifyDate`, `chuangGanCount`, `configurationInformation`, `countRmb`, `deleteStauts`, `describes`, `electrovalenceRmb`, `indexRmb`, `kongTiaoCount`, `lianDong`, `muluId`, `names`, `refundable`, `rmbType`, `statuss`, `stops`, `upgradeable`, `validPeriod`, `zhiLengMax`, `zhiLengMix`, `zhiReMax`, `zhiReMix`, `createUser_id`, `lastModifyUser_id`, `area_id`, `sensorEnabled`, `status`) VALUES ('4028e49b4b538e7e014b5395c8110001', '0', '2015-02-04 15:54:59', '2015-02-04 15:54:59', '3', '1', '8000', NULL, '虚拟空调服务', '6000', '2000', '3', '0', '1', '智能空调服务2', NULL, '1', NULL, NULL, NULL, '3', '23', '20', '32', '26', '1', '1', '2', NULL, '2');
--update spms_device(GW) storage--
update spms_device sd1 inner join (select id from spms_device where id 
in(select sd.id from spms_user su,spms_device sd where su.gw_id=sd.id)) child_table 
on sd1.id=child_table.id set storage ='5';
--update spms_device(AC) storage--

update spms_device sd1 inner join (select id from spms_device where id 
in(select sd.id from spms_user_product_binding supb,spms_device sd where supb.device_id = sd.id )) child_table 
on sd1.id=child_table.id set storage ='5';

--批量更新spms_product表中的时间--
update spms_product set subscribeDate=date_format('2015-01-01','%Y-%m-%d') ,
activateDate=date_format('2015-01-01','%Y-%m-%d'),expireDate=date_format('2015-04-01','%Y-%m-%d')
 where id in(select t.id from (select * from spms_product  order by id limit 1,25)as t)
 --批量更新spms_user中的balance和credit--
 update spms_user su inner join (select `sp`.`user_id` AS `user_id`,`spt`.`countRmb` AS `countRmb` from (`spms_product` `sp` join `spms_product_type` `spt`) where (`sp`.`type_id` = `spt`.`id`)) rt on rt.user_id = su.id set su.balance=rt.countRmb ,credit=rt.countRmb where  su.id = rt.user_id ;
