// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgdef/debug.proto

package com.harmazing.protobuf;

public final class DebugProtos {
  private DebugProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConnectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string type = 1;
    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // required string mac = 2;
    /**
     * <code>required string mac = 2;</code>
     */
    boolean hasMac();
    /**
     * <code>required string mac = 2;</code>
     */
    java.lang.String getMac();
    /**
     * <code>required string mac = 2;</code>
     */
    com.google.protobuf.ByteString
        getMacBytes();
  }
  /**
   * Protobuf type {@code protobuf.Connect}
   */
  public static final class Connect extends
      com.google.protobuf.GeneratedMessage
      implements ConnectOrBuilder {
    // Use Connect.newBuilder() to construct.
    private Connect(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Connect(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Connect defaultInstance;
    public static Connect getDefaultInstance() {
      return defaultInstance;
    }

    public Connect getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Connect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              mac_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Connect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Connect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.harmazing.protobuf.DebugProtos.Connect.class, com.harmazing.protobuf.DebugProtos.Connect.Builder.class);
    }

    public static com.google.protobuf.Parser<Connect> PARSER =
        new com.google.protobuf.AbstractParser<Connect>() {
      public Connect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Connect(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Connect> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string mac = 2;
    public static final int MAC_FIELD_NUMBER = 2;
    private java.lang.Object mac_;
    /**
     * <code>required string mac = 2;</code>
     */
    public boolean hasMac() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string mac = 2;</code>
     */
    public java.lang.String getMac() {
      java.lang.Object ref = mac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mac_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mac = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMacBytes() {
      java.lang.Object ref = mac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = "";
      mac_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMac()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMacBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMacBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.harmazing.protobuf.DebugProtos.Connect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.DebugProtos.Connect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Connect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.DebugProtos.Connect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Connect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Connect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Connect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Connect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Connect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Connect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.harmazing.protobuf.DebugProtos.Connect prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Connect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.harmazing.protobuf.DebugProtos.ConnectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Connect_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Connect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.harmazing.protobuf.DebugProtos.Connect.class, com.harmazing.protobuf.DebugProtos.Connect.Builder.class);
      }

      // Construct using com.harmazing.protobuf.DebugProtos.Connect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        mac_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Connect_descriptor;
      }

      public com.harmazing.protobuf.DebugProtos.Connect getDefaultInstanceForType() {
        return com.harmazing.protobuf.DebugProtos.Connect.getDefaultInstance();
      }

      public com.harmazing.protobuf.DebugProtos.Connect build() {
        com.harmazing.protobuf.DebugProtos.Connect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.harmazing.protobuf.DebugProtos.Connect buildPartial() {
        com.harmazing.protobuf.DebugProtos.Connect result = new com.harmazing.protobuf.DebugProtos.Connect(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mac_ = mac_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.harmazing.protobuf.DebugProtos.Connect) {
          return mergeFrom((com.harmazing.protobuf.DebugProtos.Connect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.harmazing.protobuf.DebugProtos.Connect other) {
        if (other == com.harmazing.protobuf.DebugProtos.Connect.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasMac()) {
          bitField0_ |= 0x00000002;
          mac_ = other.mac_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasMac()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.harmazing.protobuf.DebugProtos.Connect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.harmazing.protobuf.DebugProtos.Connect) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string type = 1;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      // required string mac = 2;
      private java.lang.Object mac_ = "";
      /**
       * <code>required string mac = 2;</code>
       */
      public boolean hasMac() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string mac = 2;</code>
       */
      public java.lang.String getMac() {
        java.lang.Object ref = mac_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string mac = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMacBytes() {
        java.lang.Object ref = mac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mac = 2;</code>
       */
      public Builder setMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string mac = 2;</code>
       */
      public Builder clearMac() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      /**
       * <code>required string mac = 2;</code>
       */
      public Builder setMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mac_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Connect)
    }

    static {
      defaultInstance = new Connect(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Connect)
  }

  public interface DisconnectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string type = 1;
    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code protobuf.Disconnect}
   */
  public static final class Disconnect extends
      com.google.protobuf.GeneratedMessage
      implements DisconnectOrBuilder {
    // Use Disconnect.newBuilder() to construct.
    private Disconnect(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Disconnect(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Disconnect defaultInstance;
    public static Disconnect getDefaultInstance() {
      return defaultInstance;
    }

    public Disconnect getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Disconnect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Disconnect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Disconnect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.harmazing.protobuf.DebugProtos.Disconnect.class, com.harmazing.protobuf.DebugProtos.Disconnect.Builder.class);
    }

    public static com.google.protobuf.Parser<Disconnect> PARSER =
        new com.google.protobuf.AbstractParser<Disconnect>() {
      public Disconnect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Disconnect(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Disconnect> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.harmazing.protobuf.DebugProtos.Disconnect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.DebugProtos.Disconnect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Disconnect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.DebugProtos.Disconnect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Disconnect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Disconnect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Disconnect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Disconnect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Disconnect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Disconnect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.harmazing.protobuf.DebugProtos.Disconnect prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Disconnect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.harmazing.protobuf.DebugProtos.DisconnectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Disconnect_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Disconnect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.harmazing.protobuf.DebugProtos.Disconnect.class, com.harmazing.protobuf.DebugProtos.Disconnect.Builder.class);
      }

      // Construct using com.harmazing.protobuf.DebugProtos.Disconnect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Disconnect_descriptor;
      }

      public com.harmazing.protobuf.DebugProtos.Disconnect getDefaultInstanceForType() {
        return com.harmazing.protobuf.DebugProtos.Disconnect.getDefaultInstance();
      }

      public com.harmazing.protobuf.DebugProtos.Disconnect build() {
        com.harmazing.protobuf.DebugProtos.Disconnect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.harmazing.protobuf.DebugProtos.Disconnect buildPartial() {
        com.harmazing.protobuf.DebugProtos.Disconnect result = new com.harmazing.protobuf.DebugProtos.Disconnect(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.harmazing.protobuf.DebugProtos.Disconnect) {
          return mergeFrom((com.harmazing.protobuf.DebugProtos.Disconnect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.harmazing.protobuf.DebugProtos.Disconnect other) {
        if (other == com.harmazing.protobuf.DebugProtos.Disconnect.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.harmazing.protobuf.DebugProtos.Disconnect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.harmazing.protobuf.DebugProtos.Disconnect) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string type = 1;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Disconnect)
    }

    static {
      defaultInstance = new Disconnect(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Disconnect)
  }

  public interface TextOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string type = 1;
    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // required string msg = 2;
    /**
     * <code>required string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>required string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code protobuf.Text}
   */
  public static final class Text extends
      com.google.protobuf.GeneratedMessage
      implements TextOrBuilder {
    // Use Text.newBuilder() to construct.
    private Text(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Text(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Text defaultInstance;
    public static Text getDefaultInstance() {
      return defaultInstance;
    }

    public Text getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Text(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Text_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Text_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.harmazing.protobuf.DebugProtos.Text.class, com.harmazing.protobuf.DebugProtos.Text.Builder.class);
    }

    public static com.google.protobuf.Parser<Text> PARSER =
        new com.google.protobuf.AbstractParser<Text>() {
      public Text parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Text(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Text> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.Object msg_;
    /**
     * <code>required string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = "";
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.harmazing.protobuf.DebugProtos.Text parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.DebugProtos.Text parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Text parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.DebugProtos.Text parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Text parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Text parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Text parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Text parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Text parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Text parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.harmazing.protobuf.DebugProtos.Text prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Text}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.harmazing.protobuf.DebugProtos.TextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Text_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Text_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.harmazing.protobuf.DebugProtos.Text.class, com.harmazing.protobuf.DebugProtos.Text.Builder.class);
      }

      // Construct using com.harmazing.protobuf.DebugProtos.Text.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Text_descriptor;
      }

      public com.harmazing.protobuf.DebugProtos.Text getDefaultInstanceForType() {
        return com.harmazing.protobuf.DebugProtos.Text.getDefaultInstance();
      }

      public com.harmazing.protobuf.DebugProtos.Text build() {
        com.harmazing.protobuf.DebugProtos.Text result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.harmazing.protobuf.DebugProtos.Text buildPartial() {
        com.harmazing.protobuf.DebugProtos.Text result = new com.harmazing.protobuf.DebugProtos.Text(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.harmazing.protobuf.DebugProtos.Text) {
          return mergeFrom((com.harmazing.protobuf.DebugProtos.Text)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.harmazing.protobuf.DebugProtos.Text other) {
        if (other == com.harmazing.protobuf.DebugProtos.Text.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.harmazing.protobuf.DebugProtos.Text parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.harmazing.protobuf.DebugProtos.Text) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string type = 1;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      // required string msg = 2;
      private java.lang.Object msg_ = "";
      /**
       * <code>required string msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Text)
    }

    static {
      defaultInstance = new Text(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Text)
  }

  public interface DebugOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .protobuf.Connect connect = 1;
    /**
     * <code>optional .protobuf.Connect connect = 1;</code>
     */
    boolean hasConnect();
    /**
     * <code>optional .protobuf.Connect connect = 1;</code>
     */
    com.harmazing.protobuf.DebugProtos.Connect getConnect();
    /**
     * <code>optional .protobuf.Connect connect = 1;</code>
     */
    com.harmazing.protobuf.DebugProtos.ConnectOrBuilder getConnectOrBuilder();

    // optional .protobuf.Disconnect disconnect = 2;
    /**
     * <code>optional .protobuf.Disconnect disconnect = 2;</code>
     */
    boolean hasDisconnect();
    /**
     * <code>optional .protobuf.Disconnect disconnect = 2;</code>
     */
    com.harmazing.protobuf.DebugProtos.Disconnect getDisconnect();
    /**
     * <code>optional .protobuf.Disconnect disconnect = 2;</code>
     */
    com.harmazing.protobuf.DebugProtos.DisconnectOrBuilder getDisconnectOrBuilder();

    // optional .protobuf.Text text = 3;
    /**
     * <code>optional .protobuf.Text text = 3;</code>
     */
    boolean hasText();
    /**
     * <code>optional .protobuf.Text text = 3;</code>
     */
    com.harmazing.protobuf.DebugProtos.Text getText();
    /**
     * <code>optional .protobuf.Text text = 3;</code>
     */
    com.harmazing.protobuf.DebugProtos.TextOrBuilder getTextOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.Debug}
   */
  public static final class Debug extends
      com.google.protobuf.GeneratedMessage
      implements DebugOrBuilder {
    // Use Debug.newBuilder() to construct.
    private Debug(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Debug(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Debug defaultInstance;
    public static Debug getDefaultInstance() {
      return defaultInstance;
    }

    public Debug getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Debug(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.harmazing.protobuf.DebugProtos.Connect.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = connect_.toBuilder();
              }
              connect_ = input.readMessage(com.harmazing.protobuf.DebugProtos.Connect.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(connect_);
                connect_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.harmazing.protobuf.DebugProtos.Disconnect.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = disconnect_.toBuilder();
              }
              disconnect_ = input.readMessage(com.harmazing.protobuf.DebugProtos.Disconnect.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(disconnect_);
                disconnect_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.harmazing.protobuf.DebugProtos.Text.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = text_.toBuilder();
              }
              text_ = input.readMessage(com.harmazing.protobuf.DebugProtos.Text.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(text_);
                text_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Debug_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Debug_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.harmazing.protobuf.DebugProtos.Debug.class, com.harmazing.protobuf.DebugProtos.Debug.Builder.class);
    }

    public static com.google.protobuf.Parser<Debug> PARSER =
        new com.google.protobuf.AbstractParser<Debug>() {
      public Debug parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Debug(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Debug> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .protobuf.Connect connect = 1;
    public static final int CONNECT_FIELD_NUMBER = 1;
    private com.harmazing.protobuf.DebugProtos.Connect connect_;
    /**
     * <code>optional .protobuf.Connect connect = 1;</code>
     */
    public boolean hasConnect() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .protobuf.Connect connect = 1;</code>
     */
    public com.harmazing.protobuf.DebugProtos.Connect getConnect() {
      return connect_;
    }
    /**
     * <code>optional .protobuf.Connect connect = 1;</code>
     */
    public com.harmazing.protobuf.DebugProtos.ConnectOrBuilder getConnectOrBuilder() {
      return connect_;
    }

    // optional .protobuf.Disconnect disconnect = 2;
    public static final int DISCONNECT_FIELD_NUMBER = 2;
    private com.harmazing.protobuf.DebugProtos.Disconnect disconnect_;
    /**
     * <code>optional .protobuf.Disconnect disconnect = 2;</code>
     */
    public boolean hasDisconnect() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .protobuf.Disconnect disconnect = 2;</code>
     */
    public com.harmazing.protobuf.DebugProtos.Disconnect getDisconnect() {
      return disconnect_;
    }
    /**
     * <code>optional .protobuf.Disconnect disconnect = 2;</code>
     */
    public com.harmazing.protobuf.DebugProtos.DisconnectOrBuilder getDisconnectOrBuilder() {
      return disconnect_;
    }

    // optional .protobuf.Text text = 3;
    public static final int TEXT_FIELD_NUMBER = 3;
    private com.harmazing.protobuf.DebugProtos.Text text_;
    /**
     * <code>optional .protobuf.Text text = 3;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .protobuf.Text text = 3;</code>
     */
    public com.harmazing.protobuf.DebugProtos.Text getText() {
      return text_;
    }
    /**
     * <code>optional .protobuf.Text text = 3;</code>
     */
    public com.harmazing.protobuf.DebugProtos.TextOrBuilder getTextOrBuilder() {
      return text_;
    }

    private void initFields() {
      connect_ = com.harmazing.protobuf.DebugProtos.Connect.getDefaultInstance();
      disconnect_ = com.harmazing.protobuf.DebugProtos.Disconnect.getDefaultInstance();
      text_ = com.harmazing.protobuf.DebugProtos.Text.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasConnect()) {
        if (!getConnect().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasDisconnect()) {
        if (!getDisconnect().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasText()) {
        if (!getText().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, connect_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, disconnect_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, text_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, connect_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, disconnect_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, text_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.harmazing.protobuf.DebugProtos.Debug parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.DebugProtos.Debug parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Debug parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.DebugProtos.Debug parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Debug parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Debug parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Debug parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Debug parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.DebugProtos.Debug parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.DebugProtos.Debug parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.harmazing.protobuf.DebugProtos.Debug prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Debug}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.harmazing.protobuf.DebugProtos.DebugOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Debug_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Debug_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.harmazing.protobuf.DebugProtos.Debug.class, com.harmazing.protobuf.DebugProtos.Debug.Builder.class);
      }

      // Construct using com.harmazing.protobuf.DebugProtos.Debug.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getConnectFieldBuilder();
          getDisconnectFieldBuilder();
          getTextFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (connectBuilder_ == null) {
          connect_ = com.harmazing.protobuf.DebugProtos.Connect.getDefaultInstance();
        } else {
          connectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (disconnectBuilder_ == null) {
          disconnect_ = com.harmazing.protobuf.DebugProtos.Disconnect.getDefaultInstance();
        } else {
          disconnectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (textBuilder_ == null) {
          text_ = com.harmazing.protobuf.DebugProtos.Text.getDefaultInstance();
        } else {
          textBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.harmazing.protobuf.DebugProtos.internal_static_protobuf_Debug_descriptor;
      }

      public com.harmazing.protobuf.DebugProtos.Debug getDefaultInstanceForType() {
        return com.harmazing.protobuf.DebugProtos.Debug.getDefaultInstance();
      }

      public com.harmazing.protobuf.DebugProtos.Debug build() {
        com.harmazing.protobuf.DebugProtos.Debug result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.harmazing.protobuf.DebugProtos.Debug buildPartial() {
        com.harmazing.protobuf.DebugProtos.Debug result = new com.harmazing.protobuf.DebugProtos.Debug(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (connectBuilder_ == null) {
          result.connect_ = connect_;
        } else {
          result.connect_ = connectBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (disconnectBuilder_ == null) {
          result.disconnect_ = disconnect_;
        } else {
          result.disconnect_ = disconnectBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (textBuilder_ == null) {
          result.text_ = text_;
        } else {
          result.text_ = textBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.harmazing.protobuf.DebugProtos.Debug) {
          return mergeFrom((com.harmazing.protobuf.DebugProtos.Debug)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.harmazing.protobuf.DebugProtos.Debug other) {
        if (other == com.harmazing.protobuf.DebugProtos.Debug.getDefaultInstance()) return this;
        if (other.hasConnect()) {
          mergeConnect(other.getConnect());
        }
        if (other.hasDisconnect()) {
          mergeDisconnect(other.getDisconnect());
        }
        if (other.hasText()) {
          mergeText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasConnect()) {
          if (!getConnect().isInitialized()) {
            
            return false;
          }
        }
        if (hasDisconnect()) {
          if (!getDisconnect().isInitialized()) {
            
            return false;
          }
        }
        if (hasText()) {
          if (!getText().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.harmazing.protobuf.DebugProtos.Debug parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.harmazing.protobuf.DebugProtos.Debug) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .protobuf.Connect connect = 1;
      private com.harmazing.protobuf.DebugProtos.Connect connect_ = com.harmazing.protobuf.DebugProtos.Connect.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.harmazing.protobuf.DebugProtos.Connect, com.harmazing.protobuf.DebugProtos.Connect.Builder, com.harmazing.protobuf.DebugProtos.ConnectOrBuilder> connectBuilder_;
      /**
       * <code>optional .protobuf.Connect connect = 1;</code>
       */
      public boolean hasConnect() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .protobuf.Connect connect = 1;</code>
       */
      public com.harmazing.protobuf.DebugProtos.Connect getConnect() {
        if (connectBuilder_ == null) {
          return connect_;
        } else {
          return connectBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.Connect connect = 1;</code>
       */
      public Builder setConnect(com.harmazing.protobuf.DebugProtos.Connect value) {
        if (connectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          connect_ = value;
          onChanged();
        } else {
          connectBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.Connect connect = 1;</code>
       */
      public Builder setConnect(
          com.harmazing.protobuf.DebugProtos.Connect.Builder builderForValue) {
        if (connectBuilder_ == null) {
          connect_ = builderForValue.build();
          onChanged();
        } else {
          connectBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.Connect connect = 1;</code>
       */
      public Builder mergeConnect(com.harmazing.protobuf.DebugProtos.Connect value) {
        if (connectBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              connect_ != com.harmazing.protobuf.DebugProtos.Connect.getDefaultInstance()) {
            connect_ =
              com.harmazing.protobuf.DebugProtos.Connect.newBuilder(connect_).mergeFrom(value).buildPartial();
          } else {
            connect_ = value;
          }
          onChanged();
        } else {
          connectBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.Connect connect = 1;</code>
       */
      public Builder clearConnect() {
        if (connectBuilder_ == null) {
          connect_ = com.harmazing.protobuf.DebugProtos.Connect.getDefaultInstance();
          onChanged();
        } else {
          connectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .protobuf.Connect connect = 1;</code>
       */
      public com.harmazing.protobuf.DebugProtos.Connect.Builder getConnectBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getConnectFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.Connect connect = 1;</code>
       */
      public com.harmazing.protobuf.DebugProtos.ConnectOrBuilder getConnectOrBuilder() {
        if (connectBuilder_ != null) {
          return connectBuilder_.getMessageOrBuilder();
        } else {
          return connect_;
        }
      }
      /**
       * <code>optional .protobuf.Connect connect = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.harmazing.protobuf.DebugProtos.Connect, com.harmazing.protobuf.DebugProtos.Connect.Builder, com.harmazing.protobuf.DebugProtos.ConnectOrBuilder> 
          getConnectFieldBuilder() {
        if (connectBuilder_ == null) {
          connectBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.harmazing.protobuf.DebugProtos.Connect, com.harmazing.protobuf.DebugProtos.Connect.Builder, com.harmazing.protobuf.DebugProtos.ConnectOrBuilder>(
                  connect_,
                  getParentForChildren(),
                  isClean());
          connect_ = null;
        }
        return connectBuilder_;
      }

      // optional .protobuf.Disconnect disconnect = 2;
      private com.harmazing.protobuf.DebugProtos.Disconnect disconnect_ = com.harmazing.protobuf.DebugProtos.Disconnect.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.harmazing.protobuf.DebugProtos.Disconnect, com.harmazing.protobuf.DebugProtos.Disconnect.Builder, com.harmazing.protobuf.DebugProtos.DisconnectOrBuilder> disconnectBuilder_;
      /**
       * <code>optional .protobuf.Disconnect disconnect = 2;</code>
       */
      public boolean hasDisconnect() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .protobuf.Disconnect disconnect = 2;</code>
       */
      public com.harmazing.protobuf.DebugProtos.Disconnect getDisconnect() {
        if (disconnectBuilder_ == null) {
          return disconnect_;
        } else {
          return disconnectBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.Disconnect disconnect = 2;</code>
       */
      public Builder setDisconnect(com.harmazing.protobuf.DebugProtos.Disconnect value) {
        if (disconnectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          disconnect_ = value;
          onChanged();
        } else {
          disconnectBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protobuf.Disconnect disconnect = 2;</code>
       */
      public Builder setDisconnect(
          com.harmazing.protobuf.DebugProtos.Disconnect.Builder builderForValue) {
        if (disconnectBuilder_ == null) {
          disconnect_ = builderForValue.build();
          onChanged();
        } else {
          disconnectBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protobuf.Disconnect disconnect = 2;</code>
       */
      public Builder mergeDisconnect(com.harmazing.protobuf.DebugProtos.Disconnect value) {
        if (disconnectBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              disconnect_ != com.harmazing.protobuf.DebugProtos.Disconnect.getDefaultInstance()) {
            disconnect_ =
              com.harmazing.protobuf.DebugProtos.Disconnect.newBuilder(disconnect_).mergeFrom(value).buildPartial();
          } else {
            disconnect_ = value;
          }
          onChanged();
        } else {
          disconnectBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protobuf.Disconnect disconnect = 2;</code>
       */
      public Builder clearDisconnect() {
        if (disconnectBuilder_ == null) {
          disconnect_ = com.harmazing.protobuf.DebugProtos.Disconnect.getDefaultInstance();
          onChanged();
        } else {
          disconnectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .protobuf.Disconnect disconnect = 2;</code>
       */
      public com.harmazing.protobuf.DebugProtos.Disconnect.Builder getDisconnectBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDisconnectFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.Disconnect disconnect = 2;</code>
       */
      public com.harmazing.protobuf.DebugProtos.DisconnectOrBuilder getDisconnectOrBuilder() {
        if (disconnectBuilder_ != null) {
          return disconnectBuilder_.getMessageOrBuilder();
        } else {
          return disconnect_;
        }
      }
      /**
       * <code>optional .protobuf.Disconnect disconnect = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.harmazing.protobuf.DebugProtos.Disconnect, com.harmazing.protobuf.DebugProtos.Disconnect.Builder, com.harmazing.protobuf.DebugProtos.DisconnectOrBuilder> 
          getDisconnectFieldBuilder() {
        if (disconnectBuilder_ == null) {
          disconnectBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.harmazing.protobuf.DebugProtos.Disconnect, com.harmazing.protobuf.DebugProtos.Disconnect.Builder, com.harmazing.protobuf.DebugProtos.DisconnectOrBuilder>(
                  disconnect_,
                  getParentForChildren(),
                  isClean());
          disconnect_ = null;
        }
        return disconnectBuilder_;
      }

      // optional .protobuf.Text text = 3;
      private com.harmazing.protobuf.DebugProtos.Text text_ = com.harmazing.protobuf.DebugProtos.Text.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.harmazing.protobuf.DebugProtos.Text, com.harmazing.protobuf.DebugProtos.Text.Builder, com.harmazing.protobuf.DebugProtos.TextOrBuilder> textBuilder_;
      /**
       * <code>optional .protobuf.Text text = 3;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .protobuf.Text text = 3;</code>
       */
      public com.harmazing.protobuf.DebugProtos.Text getText() {
        if (textBuilder_ == null) {
          return text_;
        } else {
          return textBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.Text text = 3;</code>
       */
      public Builder setText(com.harmazing.protobuf.DebugProtos.Text value) {
        if (textBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          text_ = value;
          onChanged();
        } else {
          textBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .protobuf.Text text = 3;</code>
       */
      public Builder setText(
          com.harmazing.protobuf.DebugProtos.Text.Builder builderForValue) {
        if (textBuilder_ == null) {
          text_ = builderForValue.build();
          onChanged();
        } else {
          textBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .protobuf.Text text = 3;</code>
       */
      public Builder mergeText(com.harmazing.protobuf.DebugProtos.Text value) {
        if (textBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              text_ != com.harmazing.protobuf.DebugProtos.Text.getDefaultInstance()) {
            text_ =
              com.harmazing.protobuf.DebugProtos.Text.newBuilder(text_).mergeFrom(value).buildPartial();
          } else {
            text_ = value;
          }
          onChanged();
        } else {
          textBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .protobuf.Text text = 3;</code>
       */
      public Builder clearText() {
        if (textBuilder_ == null) {
          text_ = com.harmazing.protobuf.DebugProtos.Text.getDefaultInstance();
          onChanged();
        } else {
          textBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .protobuf.Text text = 3;</code>
       */
      public com.harmazing.protobuf.DebugProtos.Text.Builder getTextBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTextFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.Text text = 3;</code>
       */
      public com.harmazing.protobuf.DebugProtos.TextOrBuilder getTextOrBuilder() {
        if (textBuilder_ != null) {
          return textBuilder_.getMessageOrBuilder();
        } else {
          return text_;
        }
      }
      /**
       * <code>optional .protobuf.Text text = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.harmazing.protobuf.DebugProtos.Text, com.harmazing.protobuf.DebugProtos.Text.Builder, com.harmazing.protobuf.DebugProtos.TextOrBuilder> 
          getTextFieldBuilder() {
        if (textBuilder_ == null) {
          textBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.harmazing.protobuf.DebugProtos.Text, com.harmazing.protobuf.DebugProtos.Text.Builder, com.harmazing.protobuf.DebugProtos.TextOrBuilder>(
                  text_,
                  getParentForChildren(),
                  isClean());
          text_ = null;
        }
        return textBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Debug)
    }

    static {
      defaultInstance = new Debug(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Debug)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Connect_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Connect_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Disconnect_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Disconnect_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Text_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Text_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Debug_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Debug_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022msgdef/debug.proto\022\010protobuf\"$\n\007Connec" +
      "t\022\014\n\004type\030\001 \002(\t\022\013\n\003mac\030\002 \002(\t\"\032\n\nDisconne" +
      "ct\022\014\n\004type\030\001 \002(\t\"!\n\004Text\022\014\n\004type\030\001 \002(\t\022\013" +
      "\n\003msg\030\002 \002(\t\"s\n\005Debug\022\"\n\007connect\030\001 \001(\0132\021." +
      "protobuf.Connect\022(\n\ndisconnect\030\002 \001(\0132\024.p" +
      "rotobuf.Disconnect\022\034\n\004text\030\003 \001(\0132\016.proto" +
      "buf.TextB%\n\026com.harmazing.protobufB\013Debu" +
      "gProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Connect_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Connect_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Connect_descriptor,
              new java.lang.String[] { "Type", "Mac", });
          internal_static_protobuf_Disconnect_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_Disconnect_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Disconnect_descriptor,
              new java.lang.String[] { "Type", });
          internal_static_protobuf_Text_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protobuf_Text_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Text_descriptor,
              new java.lang.String[] { "Type", "Msg", });
          internal_static_protobuf_Debug_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_protobuf_Debug_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Debug_descriptor,
              new java.lang.String[] { "Connect", "Disconnect", "Text", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
