// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgdef/event.proto

package com.harmazing.protobuf;

public final class EventProtos {
  private EventProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string source = 1;
    /**
     * <code>required string source = 1;</code>
     *
     * <pre>
     * source of event
     * </pre>
     */
    boolean hasSource();
    /**
     * <code>required string source = 1;</code>
     *
     * <pre>
     * source of event
     * </pre>
     */
    java.lang.String getSource();
    /**
     * <code>required string source = 1;</code>
     *
     * <pre>
     * source of event
     * </pre>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    // required .protobuf.Event.EventType type = 2;
    /**
     * <code>required .protobuf.Event.EventType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .protobuf.Event.EventType type = 2;</code>
     */
    com.harmazing.protobuf.EventProtos.Event.EventType getType();

    // optional string string_parameter = 3;
    /**
     * <code>optional string string_parameter = 3;</code>
     */
    boolean hasStringParameter();
    /**
     * <code>optional string string_parameter = 3;</code>
     */
    java.lang.String getStringParameter();
    /**
     * <code>optional string string_parameter = 3;</code>
     */
    com.google.protobuf.ByteString
        getStringParameterBytes();

    // optional uint32 int_parameter = 4;
    /**
     * <code>optional uint32 int_parameter = 4;</code>
     */
    boolean hasIntParameter();
    /**
     * <code>optional uint32 int_parameter = 4;</code>
     */
    int getIntParameter();

    // optional bytes ac_exception = 5;
    /**
     * <code>optional bytes ac_exception = 5;</code>
     */
    boolean hasAcException();
    /**
     * <code>optional bytes ac_exception = 5;</code>
     */
    com.google.protobuf.ByteString getAcException();

    // optional .protobuf.IrPacket ir_packet = 6;
    /**
     * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
     */
    boolean hasIrPacket();
    /**
     * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
     */
    com.harmazing.protobuf.CommandProtos.IrPacket getIrPacket();
    /**
     * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
     */
    com.harmazing.protobuf.CommandProtos.IrPacketOrBuilder getIrPacketOrBuilder();

    // optional .protobuf.LampColor color = 7;
    /**
     * <code>optional .protobuf.LampColor color = 7;</code>
     */
    boolean hasColor();
    /**
     * <code>optional .protobuf.LampColor color = 7;</code>
     */
    com.harmazing.protobuf.CommandProtos.LampColor getColor();
    /**
     * <code>optional .protobuf.LampColor color = 7;</code>
     */
    com.harmazing.protobuf.CommandProtos.LampColorOrBuilder getColorOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessage
      implements EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Event(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }

    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              source_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.harmazing.protobuf.EventProtos.Event.EventType value = com.harmazing.protobuf.EventProtos.Event.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              stringParameter_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              intParameter_ = input.readUInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              acException_ = input.readBytes();
              break;
            }
            case 50: {
              com.harmazing.protobuf.CommandProtos.IrPacket.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = irPacket_.toBuilder();
              }
              irPacket_ = input.readMessage(com.harmazing.protobuf.CommandProtos.IrPacket.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(irPacket_);
                irPacket_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              com.harmazing.protobuf.CommandProtos.LampColor.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = color_.toBuilder();
              }
              color_ = input.readMessage(com.harmazing.protobuf.CommandProtos.LampColor.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(color_);
                color_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.harmazing.protobuf.EventProtos.internal_static_protobuf_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.harmazing.protobuf.EventProtos.internal_static_protobuf_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.harmazing.protobuf.EventProtos.Event.class, com.harmazing.protobuf.EventProtos.Event.Builder.class);
    }

    public static com.google.protobuf.Parser<Event> PARSER =
        new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protobuf.Event.EventType}
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SENSOR_JOIN = 0;</code>
       */
      SENSOR_JOIN(0, 0),
      /**
       * <code>SENSOR_LEAVE = 1;</code>
       */
      SENSOR_LEAVE(1, 1),
      /**
       * <code>SENSOR_PAIR = 2;</code>
       */
      SENSOR_PAIR(2, 2),
      /**
       * <code>SENSOR_UNPAIR = 3;</code>
       */
      SENSOR_UNPAIR(3, 3),
      /**
       * <code>SENSOR_PAIR_REQUEST = 4;</code>
       */
      SENSOR_PAIR_REQUEST(4, 4),
      /**
       * <code>SENSOR_BATTERY_LOW = 5;</code>
       */
      SENSOR_BATTERY_LOW(5, 5),
      /**
       * <code>SENSOR_AC_ON = 6;</code>
       */
      SENSOR_AC_ON(6, 6),
      /**
       * <code>SENSOR_AC_OFF = 7;</code>
       */
      SENSOR_AC_OFF(7, 7),
      /**
       * <code>SENSOR_AC_MODE_CHANGED = 8;</code>
       *
       * <pre>
       * op mode
       * </pre>
       */
      SENSOR_AC_MODE_CHANGED(8, 8),
      /**
       * <code>SENSOR_AC_WIND_CHANGED = 9;</code>
       *
       * <pre>
       * fan mode
       * </pre>
       */
      SENSOR_AC_WIND_CHANGED(9, 9),
      /**
       * <code>SENSOR_AC_LOCAL_TEMP_CHANGED = 10;</code>
       *
       * <pre>
       * local temperature
       * </pre>
       */
      SENSOR_AC_LOCAL_TEMP_CHANGED(10, 10),
      /**
       * <code>SENSOR_AC_TARGET_TEMP_CHANGED = 11;</code>
       *
       * <pre>
       * target temperature
       * </pre>
       */
      SENSOR_AC_TARGET_TEMP_CHANGED(11, 11),
      /**
       * <code>SENSOR_OPEN = 12;</code>
       */
      SENSOR_OPEN(12, 12),
      /**
       * <code>SENSOR_CLOSE = 13;</code>
       */
      SENSOR_CLOSE(13, 13),
      /**
       * <code>SENSOR_AC_EXCEPTION = 14;</code>
       */
      SENSOR_AC_EXCEPTION(14, 14),
      /**
       * <code>IR_CODE_RECEIVED = 15;</code>
       */
      IR_CODE_RECEIVED(15, 15),
      /**
       * <code>SENSOR_OO_ON = 16;</code>
       */
      SENSOR_OO_ON(16, 16),
      /**
       * <code>SENSOR_OO_OFF = 17;</code>
       */
      SENSOR_OO_OFF(17, 17),
      /**
       * <code>SENSOR_TEMPERATURE = 18;</code>
       */
      SENSOR_TEMPERATURE(18, 18),
      /**
       * <code>SENSOR_HUMIDITY = 19;</code>
       */
      SENSOR_HUMIDITY(19, 19),
      /**
       * <code>SENSOR_LAMP_COLOR = 20;</code>
       */
      SENSOR_LAMP_COLOR(20, 20),
      /**
       * <code>SENSOR_ALARMED = 21;</code>
       */
      SENSOR_ALARMED(21, 21),
      /**
       * <code>SENSOR_NOT_ALARMED = 22;</code>
       */
      SENSOR_NOT_ALARMED(22, 22),
      ;

      /**
       * <code>SENSOR_JOIN = 0;</code>
       */
      public static final int SENSOR_JOIN_VALUE = 0;
      /**
       * <code>SENSOR_LEAVE = 1;</code>
       */
      public static final int SENSOR_LEAVE_VALUE = 1;
      /**
       * <code>SENSOR_PAIR = 2;</code>
       */
      public static final int SENSOR_PAIR_VALUE = 2;
      /**
       * <code>SENSOR_UNPAIR = 3;</code>
       */
      public static final int SENSOR_UNPAIR_VALUE = 3;
      /**
       * <code>SENSOR_PAIR_REQUEST = 4;</code>
       */
      public static final int SENSOR_PAIR_REQUEST_VALUE = 4;
      /**
       * <code>SENSOR_BATTERY_LOW = 5;</code>
       */
      public static final int SENSOR_BATTERY_LOW_VALUE = 5;
      /**
       * <code>SENSOR_AC_ON = 6;</code>
       */
      public static final int SENSOR_AC_ON_VALUE = 6;
      /**
       * <code>SENSOR_AC_OFF = 7;</code>
       */
      public static final int SENSOR_AC_OFF_VALUE = 7;
      /**
       * <code>SENSOR_AC_MODE_CHANGED = 8;</code>
       *
       * <pre>
       * op mode
       * </pre>
       */
      public static final int SENSOR_AC_MODE_CHANGED_VALUE = 8;
      /**
       * <code>SENSOR_AC_WIND_CHANGED = 9;</code>
       *
       * <pre>
       * fan mode
       * </pre>
       */
      public static final int SENSOR_AC_WIND_CHANGED_VALUE = 9;
      /**
       * <code>SENSOR_AC_LOCAL_TEMP_CHANGED = 10;</code>
       *
       * <pre>
       * local temperature
       * </pre>
       */
      public static final int SENSOR_AC_LOCAL_TEMP_CHANGED_VALUE = 10;
      /**
       * <code>SENSOR_AC_TARGET_TEMP_CHANGED = 11;</code>
       *
       * <pre>
       * target temperature
       * </pre>
       */
      public static final int SENSOR_AC_TARGET_TEMP_CHANGED_VALUE = 11;
      /**
       * <code>SENSOR_OPEN = 12;</code>
       */
      public static final int SENSOR_OPEN_VALUE = 12;
      /**
       * <code>SENSOR_CLOSE = 13;</code>
       */
      public static final int SENSOR_CLOSE_VALUE = 13;
      /**
       * <code>SENSOR_AC_EXCEPTION = 14;</code>
       */
      public static final int SENSOR_AC_EXCEPTION_VALUE = 14;
      /**
       * <code>IR_CODE_RECEIVED = 15;</code>
       */
      public static final int IR_CODE_RECEIVED_VALUE = 15;
      /**
       * <code>SENSOR_OO_ON = 16;</code>
       */
      public static final int SENSOR_OO_ON_VALUE = 16;
      /**
       * <code>SENSOR_OO_OFF = 17;</code>
       */
      public static final int SENSOR_OO_OFF_VALUE = 17;
      /**
       * <code>SENSOR_TEMPERATURE = 18;</code>
       */
      public static final int SENSOR_TEMPERATURE_VALUE = 18;
      /**
       * <code>SENSOR_HUMIDITY = 19;</code>
       */
      public static final int SENSOR_HUMIDITY_VALUE = 19;
      /**
       * <code>SENSOR_LAMP_COLOR = 20;</code>
       */
      public static final int SENSOR_LAMP_COLOR_VALUE = 20;
      /**
       * <code>SENSOR_ALARMED = 21;</code>
       */
      public static final int SENSOR_ALARMED_VALUE = 21;
      /**
       * <code>SENSOR_NOT_ALARMED = 22;</code>
       */
      public static final int SENSOR_NOT_ALARMED_VALUE = 22;


      public final int getNumber() { return value; }

      public static EventType valueOf(int value) {
        switch (value) {
          case 0: return SENSOR_JOIN;
          case 1: return SENSOR_LEAVE;
          case 2: return SENSOR_PAIR;
          case 3: return SENSOR_UNPAIR;
          case 4: return SENSOR_PAIR_REQUEST;
          case 5: return SENSOR_BATTERY_LOW;
          case 6: return SENSOR_AC_ON;
          case 7: return SENSOR_AC_OFF;
          case 8: return SENSOR_AC_MODE_CHANGED;
          case 9: return SENSOR_AC_WIND_CHANGED;
          case 10: return SENSOR_AC_LOCAL_TEMP_CHANGED;
          case 11: return SENSOR_AC_TARGET_TEMP_CHANGED;
          case 12: return SENSOR_OPEN;
          case 13: return SENSOR_CLOSE;
          case 14: return SENSOR_AC_EXCEPTION;
          case 15: return IR_CODE_RECEIVED;
          case 16: return SENSOR_OO_ON;
          case 17: return SENSOR_OO_OFF;
          case 18: return SENSOR_TEMPERATURE;
          case 19: return SENSOR_HUMIDITY;
          case 20: return SENSOR_LAMP_COLOR;
          case 21: return SENSOR_ALARMED;
          case 22: return SENSOR_NOT_ALARMED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.harmazing.protobuf.EventProtos.Event.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EventType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Event.EventType)
    }

    private int bitField0_;
    // required string source = 1;
    public static final int SOURCE_FIELD_NUMBER = 1;
    private java.lang.Object source_;
    /**
     * <code>required string source = 1;</code>
     *
     * <pre>
     * source of event
     * </pre>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string source = 1;</code>
     *
     * <pre>
     * source of event
     * </pre>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string source = 1;</code>
     *
     * <pre>
     * source of event
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .protobuf.Event.EventType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private com.harmazing.protobuf.EventProtos.Event.EventType type_;
    /**
     * <code>required .protobuf.Event.EventType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protobuf.Event.EventType type = 2;</code>
     */
    public com.harmazing.protobuf.EventProtos.Event.EventType getType() {
      return type_;
    }

    // optional string string_parameter = 3;
    public static final int STRING_PARAMETER_FIELD_NUMBER = 3;
    private java.lang.Object stringParameter_;
    /**
     * <code>optional string string_parameter = 3;</code>
     */
    public boolean hasStringParameter() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string string_parameter = 3;</code>
     */
    public java.lang.String getStringParameter() {
      java.lang.Object ref = stringParameter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringParameter_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string string_parameter = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStringParameterBytes() {
      java.lang.Object ref = stringParameter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringParameter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 int_parameter = 4;
    public static final int INT_PARAMETER_FIELD_NUMBER = 4;
    private int intParameter_;
    /**
     * <code>optional uint32 int_parameter = 4;</code>
     */
    public boolean hasIntParameter() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 int_parameter = 4;</code>
     */
    public int getIntParameter() {
      return intParameter_;
    }

    // optional bytes ac_exception = 5;
    public static final int AC_EXCEPTION_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString acException_;
    /**
     * <code>optional bytes ac_exception = 5;</code>
     */
    public boolean hasAcException() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes ac_exception = 5;</code>
     */
    public com.google.protobuf.ByteString getAcException() {
      return acException_;
    }

    // optional .protobuf.IrPacket ir_packet = 6;
    public static final int IR_PACKET_FIELD_NUMBER = 6;
    private com.harmazing.protobuf.CommandProtos.IrPacket irPacket_;
    /**
     * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
     */
    public boolean hasIrPacket() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
     */
    public com.harmazing.protobuf.CommandProtos.IrPacket getIrPacket() {
      return irPacket_;
    }
    /**
     * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
     */
    public com.harmazing.protobuf.CommandProtos.IrPacketOrBuilder getIrPacketOrBuilder() {
      return irPacket_;
    }

    // optional .protobuf.LampColor color = 7;
    public static final int COLOR_FIELD_NUMBER = 7;
    private com.harmazing.protobuf.CommandProtos.LampColor color_;
    /**
     * <code>optional .protobuf.LampColor color = 7;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .protobuf.LampColor color = 7;</code>
     */
    public com.harmazing.protobuf.CommandProtos.LampColor getColor() {
      return color_;
    }
    /**
     * <code>optional .protobuf.LampColor color = 7;</code>
     */
    public com.harmazing.protobuf.CommandProtos.LampColorOrBuilder getColorOrBuilder() {
      return color_;
    }

    private void initFields() {
      source_ = "";
      type_ = com.harmazing.protobuf.EventProtos.Event.EventType.SENSOR_JOIN;
      stringParameter_ = "";
      intParameter_ = 0;
      acException_ = com.google.protobuf.ByteString.EMPTY;
      irPacket_ = com.harmazing.protobuf.CommandProtos.IrPacket.getDefaultInstance();
      color_ = com.harmazing.protobuf.CommandProtos.LampColor.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasIrPacket()) {
        if (!getIrPacket().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasColor()) {
        if (!getColor().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSourceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStringParameterBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, intParameter_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, acException_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, irPacket_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, color_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSourceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStringParameterBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, intParameter_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, acException_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, irPacket_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, color_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.harmazing.protobuf.EventProtos.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.EventProtos.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.EventProtos.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.EventProtos.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.EventProtos.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.EventProtos.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.EventProtos.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.harmazing.protobuf.EventProtos.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.EventProtos.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.EventProtos.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.harmazing.protobuf.EventProtos.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.harmazing.protobuf.EventProtos.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.harmazing.protobuf.EventProtos.internal_static_protobuf_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.harmazing.protobuf.EventProtos.internal_static_protobuf_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.harmazing.protobuf.EventProtos.Event.class, com.harmazing.protobuf.EventProtos.Event.Builder.class);
      }

      // Construct using com.harmazing.protobuf.EventProtos.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIrPacketFieldBuilder();
          getColorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.harmazing.protobuf.EventProtos.Event.EventType.SENSOR_JOIN;
        bitField0_ = (bitField0_ & ~0x00000002);
        stringParameter_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        intParameter_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        acException_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (irPacketBuilder_ == null) {
          irPacket_ = com.harmazing.protobuf.CommandProtos.IrPacket.getDefaultInstance();
        } else {
          irPacketBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (colorBuilder_ == null) {
          color_ = com.harmazing.protobuf.CommandProtos.LampColor.getDefaultInstance();
        } else {
          colorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.harmazing.protobuf.EventProtos.internal_static_protobuf_Event_descriptor;
      }

      public com.harmazing.protobuf.EventProtos.Event getDefaultInstanceForType() {
        return com.harmazing.protobuf.EventProtos.Event.getDefaultInstance();
      }

      public com.harmazing.protobuf.EventProtos.Event build() {
        com.harmazing.protobuf.EventProtos.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.harmazing.protobuf.EventProtos.Event buildPartial() {
        com.harmazing.protobuf.EventProtos.Event result = new com.harmazing.protobuf.EventProtos.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stringParameter_ = stringParameter_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.intParameter_ = intParameter_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.acException_ = acException_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (irPacketBuilder_ == null) {
          result.irPacket_ = irPacket_;
        } else {
          result.irPacket_ = irPacketBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (colorBuilder_ == null) {
          result.color_ = color_;
        } else {
          result.color_ = colorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.harmazing.protobuf.EventProtos.Event) {
          return mergeFrom((com.harmazing.protobuf.EventProtos.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.harmazing.protobuf.EventProtos.Event other) {
        if (other == com.harmazing.protobuf.EventProtos.Event.getDefaultInstance()) return this;
        if (other.hasSource()) {
          bitField0_ |= 0x00000001;
          source_ = other.source_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasStringParameter()) {
          bitField0_ |= 0x00000004;
          stringParameter_ = other.stringParameter_;
          onChanged();
        }
        if (other.hasIntParameter()) {
          setIntParameter(other.getIntParameter());
        }
        if (other.hasAcException()) {
          setAcException(other.getAcException());
        }
        if (other.hasIrPacket()) {
          mergeIrPacket(other.getIrPacket());
        }
        if (other.hasColor()) {
          mergeColor(other.getColor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSource()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (hasIrPacket()) {
          if (!getIrPacket().isInitialized()) {
            
            return false;
          }
        }
        if (hasColor()) {
          if (!getColor().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.harmazing.protobuf.EventProtos.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.harmazing.protobuf.EventProtos.Event) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string source = 1;
      private java.lang.Object source_ = "";
      /**
       * <code>required string source = 1;</code>
       *
       * <pre>
       * source of event
       * </pre>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string source = 1;</code>
       *
       * <pre>
       * source of event
       * </pre>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string source = 1;</code>
       *
       * <pre>
       * source of event
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string source = 1;</code>
       *
       * <pre>
       * source of event
       * </pre>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string source = 1;</code>
       *
       * <pre>
       * source of event
       * </pre>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>required string source = 1;</code>
       *
       * <pre>
       * source of event
       * </pre>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        source_ = value;
        onChanged();
        return this;
      }

      // required .protobuf.Event.EventType type = 2;
      private com.harmazing.protobuf.EventProtos.Event.EventType type_ = com.harmazing.protobuf.EventProtos.Event.EventType.SENSOR_JOIN;
      /**
       * <code>required .protobuf.Event.EventType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protobuf.Event.EventType type = 2;</code>
       */
      public com.harmazing.protobuf.EventProtos.Event.EventType getType() {
        return type_;
      }
      /**
       * <code>required .protobuf.Event.EventType type = 2;</code>
       */
      public Builder setType(com.harmazing.protobuf.EventProtos.Event.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.Event.EventType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.harmazing.protobuf.EventProtos.Event.EventType.SENSOR_JOIN;
        onChanged();
        return this;
      }

      // optional string string_parameter = 3;
      private java.lang.Object stringParameter_ = "";
      /**
       * <code>optional string string_parameter = 3;</code>
       */
      public boolean hasStringParameter() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string string_parameter = 3;</code>
       */
      public java.lang.String getStringParameter() {
        java.lang.Object ref = stringParameter_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          stringParameter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string string_parameter = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStringParameterBytes() {
        java.lang.Object ref = stringParameter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringParameter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string string_parameter = 3;</code>
       */
      public Builder setStringParameter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stringParameter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string string_parameter = 3;</code>
       */
      public Builder clearStringParameter() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stringParameter_ = getDefaultInstance().getStringParameter();
        onChanged();
        return this;
      }
      /**
       * <code>optional string string_parameter = 3;</code>
       */
      public Builder setStringParameterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stringParameter_ = value;
        onChanged();
        return this;
      }

      // optional uint32 int_parameter = 4;
      private int intParameter_ ;
      /**
       * <code>optional uint32 int_parameter = 4;</code>
       */
      public boolean hasIntParameter() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 int_parameter = 4;</code>
       */
      public int getIntParameter() {
        return intParameter_;
      }
      /**
       * <code>optional uint32 int_parameter = 4;</code>
       */
      public Builder setIntParameter(int value) {
        bitField0_ |= 0x00000008;
        intParameter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 int_parameter = 4;</code>
       */
      public Builder clearIntParameter() {
        bitField0_ = (bitField0_ & ~0x00000008);
        intParameter_ = 0;
        onChanged();
        return this;
      }

      // optional bytes ac_exception = 5;
      private com.google.protobuf.ByteString acException_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes ac_exception = 5;</code>
       */
      public boolean hasAcException() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes ac_exception = 5;</code>
       */
      public com.google.protobuf.ByteString getAcException() {
        return acException_;
      }
      /**
       * <code>optional bytes ac_exception = 5;</code>
       */
      public Builder setAcException(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        acException_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes ac_exception = 5;</code>
       */
      public Builder clearAcException() {
        bitField0_ = (bitField0_ & ~0x00000010);
        acException_ = getDefaultInstance().getAcException();
        onChanged();
        return this;
      }

      // optional .protobuf.IrPacket ir_packet = 6;
      private com.harmazing.protobuf.CommandProtos.IrPacket irPacket_ = com.harmazing.protobuf.CommandProtos.IrPacket.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.harmazing.protobuf.CommandProtos.IrPacket, com.harmazing.protobuf.CommandProtos.IrPacket.Builder, com.harmazing.protobuf.CommandProtos.IrPacketOrBuilder> irPacketBuilder_;
      /**
       * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
       */
      public boolean hasIrPacket() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
       */
      public com.harmazing.protobuf.CommandProtos.IrPacket getIrPacket() {
        if (irPacketBuilder_ == null) {
          return irPacket_;
        } else {
          return irPacketBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
       */
      public Builder setIrPacket(com.harmazing.protobuf.CommandProtos.IrPacket value) {
        if (irPacketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          irPacket_ = value;
          onChanged();
        } else {
          irPacketBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
       */
      public Builder setIrPacket(
          com.harmazing.protobuf.CommandProtos.IrPacket.Builder builderForValue) {
        if (irPacketBuilder_ == null) {
          irPacket_ = builderForValue.build();
          onChanged();
        } else {
          irPacketBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
       */
      public Builder mergeIrPacket(com.harmazing.protobuf.CommandProtos.IrPacket value) {
        if (irPacketBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              irPacket_ != com.harmazing.protobuf.CommandProtos.IrPacket.getDefaultInstance()) {
            irPacket_ =
              com.harmazing.protobuf.CommandProtos.IrPacket.newBuilder(irPacket_).mergeFrom(value).buildPartial();
          } else {
            irPacket_ = value;
          }
          onChanged();
        } else {
          irPacketBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
       */
      public Builder clearIrPacket() {
        if (irPacketBuilder_ == null) {
          irPacket_ = com.harmazing.protobuf.CommandProtos.IrPacket.getDefaultInstance();
          onChanged();
        } else {
          irPacketBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
       */
      public com.harmazing.protobuf.CommandProtos.IrPacket.Builder getIrPacketBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getIrPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
       */
      public com.harmazing.protobuf.CommandProtos.IrPacketOrBuilder getIrPacketOrBuilder() {
        if (irPacketBuilder_ != null) {
          return irPacketBuilder_.getMessageOrBuilder();
        } else {
          return irPacket_;
        }
      }
      /**
       * <code>optional .protobuf.IrPacket ir_packet = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.harmazing.protobuf.CommandProtos.IrPacket, com.harmazing.protobuf.CommandProtos.IrPacket.Builder, com.harmazing.protobuf.CommandProtos.IrPacketOrBuilder> 
          getIrPacketFieldBuilder() {
        if (irPacketBuilder_ == null) {
          irPacketBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.harmazing.protobuf.CommandProtos.IrPacket, com.harmazing.protobuf.CommandProtos.IrPacket.Builder, com.harmazing.protobuf.CommandProtos.IrPacketOrBuilder>(
                  irPacket_,
                  getParentForChildren(),
                  isClean());
          irPacket_ = null;
        }
        return irPacketBuilder_;
      }

      // optional .protobuf.LampColor color = 7;
      private com.harmazing.protobuf.CommandProtos.LampColor color_ = com.harmazing.protobuf.CommandProtos.LampColor.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.harmazing.protobuf.CommandProtos.LampColor, com.harmazing.protobuf.CommandProtos.LampColor.Builder, com.harmazing.protobuf.CommandProtos.LampColorOrBuilder> colorBuilder_;
      /**
       * <code>optional .protobuf.LampColor color = 7;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .protobuf.LampColor color = 7;</code>
       */
      public com.harmazing.protobuf.CommandProtos.LampColor getColor() {
        if (colorBuilder_ == null) {
          return color_;
        } else {
          return colorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.LampColor color = 7;</code>
       */
      public Builder setColor(com.harmazing.protobuf.CommandProtos.LampColor value) {
        if (colorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          color_ = value;
          onChanged();
        } else {
          colorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .protobuf.LampColor color = 7;</code>
       */
      public Builder setColor(
          com.harmazing.protobuf.CommandProtos.LampColor.Builder builderForValue) {
        if (colorBuilder_ == null) {
          color_ = builderForValue.build();
          onChanged();
        } else {
          colorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .protobuf.LampColor color = 7;</code>
       */
      public Builder mergeColor(com.harmazing.protobuf.CommandProtos.LampColor value) {
        if (colorBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              color_ != com.harmazing.protobuf.CommandProtos.LampColor.getDefaultInstance()) {
            color_ =
              com.harmazing.protobuf.CommandProtos.LampColor.newBuilder(color_).mergeFrom(value).buildPartial();
          } else {
            color_ = value;
          }
          onChanged();
        } else {
          colorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .protobuf.LampColor color = 7;</code>
       */
      public Builder clearColor() {
        if (colorBuilder_ == null) {
          color_ = com.harmazing.protobuf.CommandProtos.LampColor.getDefaultInstance();
          onChanged();
        } else {
          colorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .protobuf.LampColor color = 7;</code>
       */
      public com.harmazing.protobuf.CommandProtos.LampColor.Builder getColorBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getColorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.LampColor color = 7;</code>
       */
      public com.harmazing.protobuf.CommandProtos.LampColorOrBuilder getColorOrBuilder() {
        if (colorBuilder_ != null) {
          return colorBuilder_.getMessageOrBuilder();
        } else {
          return color_;
        }
      }
      /**
       * <code>optional .protobuf.LampColor color = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.harmazing.protobuf.CommandProtos.LampColor, com.harmazing.protobuf.CommandProtos.LampColor.Builder, com.harmazing.protobuf.CommandProtos.LampColorOrBuilder> 
          getColorFieldBuilder() {
        if (colorBuilder_ == null) {
          colorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.harmazing.protobuf.CommandProtos.LampColor, com.harmazing.protobuf.CommandProtos.LampColor.Builder, com.harmazing.protobuf.CommandProtos.LampColorOrBuilder>(
                  color_,
                  getParentForChildren(),
                  isClean());
          color_ = null;
        }
        return colorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Event)
    }

    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Event)
  }

  public interface EventReportOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .protobuf.Event events = 1;
    /**
     * <code>repeated .protobuf.Event events = 1;</code>
     */
    java.util.List<com.harmazing.protobuf.EventProtos.Event> 
        getEventsList();
    /**
     * <code>repeated .protobuf.Event events = 1;</code>
     */
    com.harmazing.protobuf.EventProtos.Event getEvents(int index);
    /**
     * <code>repeated .protobuf.Event events = 1;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated .protobuf.Event events = 1;</code>
     */
    java.util.List<? extends com.harmazing.protobuf.EventProtos.EventOrBuilder> 
        getEventsOrBuilderList();
    /**
     * <code>repeated .protobuf.Event events = 1;</code>
     */
    com.harmazing.protobuf.EventProtos.EventOrBuilder getEventsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.EventReport}
   */
  public static final class EventReport extends
      com.google.protobuf.GeneratedMessage
      implements EventReportOrBuilder {
    // Use EventReport.newBuilder() to construct.
    private EventReport(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventReport(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EventReport defaultInstance;
    public static EventReport getDefaultInstance() {
      return defaultInstance;
    }

    public EventReport getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EventReport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                events_ = new java.util.ArrayList<com.harmazing.protobuf.EventProtos.Event>();
                mutable_bitField0_ |= 0x00000001;
              }
              events_.add(input.readMessage(com.harmazing.protobuf.EventProtos.Event.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.harmazing.protobuf.EventProtos.internal_static_protobuf_EventReport_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.harmazing.protobuf.EventProtos.internal_static_protobuf_EventReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.harmazing.protobuf.EventProtos.EventReport.class, com.harmazing.protobuf.EventProtos.EventReport.Builder.class);
    }

    public static com.google.protobuf.Parser<EventReport> PARSER =
        new com.google.protobuf.AbstractParser<EventReport>() {
      public EventReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventReport(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EventReport> getParserForType() {
      return PARSER;
    }

    // repeated .protobuf.Event events = 1;
    public static final int EVENTS_FIELD_NUMBER = 1;
    private java.util.List<com.harmazing.protobuf.EventProtos.Event> events_;
    /**
     * <code>repeated .protobuf.Event events = 1;</code>
     */
    public java.util.List<com.harmazing.protobuf.EventProtos.Event> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .protobuf.Event events = 1;</code>
     */
    public java.util.List<? extends com.harmazing.protobuf.EventProtos.EventOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .protobuf.Event events = 1;</code>
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .protobuf.Event events = 1;</code>
     */
    public com.harmazing.protobuf.EventProtos.Event getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .protobuf.Event events = 1;</code>
     */
    public com.harmazing.protobuf.EventProtos.EventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }

    private void initFields() {
      events_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getEventsCount(); i++) {
        if (!getEvents(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < events_.size(); i++) {
        output.writeMessage(1, events_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < events_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, events_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.harmazing.protobuf.EventProtos.EventReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.EventProtos.EventReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.EventProtos.EventReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.EventProtos.EventReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.EventProtos.EventReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.EventProtos.EventReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.EventProtos.EventReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.harmazing.protobuf.EventProtos.EventReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.EventProtos.EventReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.EventProtos.EventReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.harmazing.protobuf.EventProtos.EventReport prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.EventReport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.harmazing.protobuf.EventProtos.EventReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.harmazing.protobuf.EventProtos.internal_static_protobuf_EventReport_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.harmazing.protobuf.EventProtos.internal_static_protobuf_EventReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.harmazing.protobuf.EventProtos.EventReport.class, com.harmazing.protobuf.EventProtos.EventReport.Builder.class);
      }

      // Construct using com.harmazing.protobuf.EventProtos.EventReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEventsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.harmazing.protobuf.EventProtos.internal_static_protobuf_EventReport_descriptor;
      }

      public com.harmazing.protobuf.EventProtos.EventReport getDefaultInstanceForType() {
        return com.harmazing.protobuf.EventProtos.EventReport.getDefaultInstance();
      }

      public com.harmazing.protobuf.EventProtos.EventReport build() {
        com.harmazing.protobuf.EventProtos.EventReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.harmazing.protobuf.EventProtos.EventReport buildPartial() {
        com.harmazing.protobuf.EventProtos.EventReport result = new com.harmazing.protobuf.EventProtos.EventReport(this);
        int from_bitField0_ = bitField0_;
        if (eventsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            events_ = java.util.Collections.unmodifiableList(events_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.events_ = events_;
        } else {
          result.events_ = eventsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.harmazing.protobuf.EventProtos.EventReport) {
          return mergeFrom((com.harmazing.protobuf.EventProtos.EventReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.harmazing.protobuf.EventProtos.EventReport other) {
        if (other == com.harmazing.protobuf.EventProtos.EventReport.getDefaultInstance()) return this;
        if (eventsBuilder_ == null) {
          if (!other.events_.isEmpty()) {
            if (events_.isEmpty()) {
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEventsIsMutable();
              events_.addAll(other.events_);
            }
            onChanged();
          }
        } else {
          if (!other.events_.isEmpty()) {
            if (eventsBuilder_.isEmpty()) {
              eventsBuilder_.dispose();
              eventsBuilder_ = null;
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000001);
              eventsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEventsFieldBuilder() : null;
            } else {
              eventsBuilder_.addAllMessages(other.events_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getEventsCount(); i++) {
          if (!getEvents(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.harmazing.protobuf.EventProtos.EventReport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.harmazing.protobuf.EventProtos.EventReport) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .protobuf.Event events = 1;
      private java.util.List<com.harmazing.protobuf.EventProtos.Event> events_ =
        java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          events_ = new java.util.ArrayList<com.harmazing.protobuf.EventProtos.Event>(events_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.harmazing.protobuf.EventProtos.Event, com.harmazing.protobuf.EventProtos.Event.Builder, com.harmazing.protobuf.EventProtos.EventOrBuilder> eventsBuilder_;

      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public java.util.List<com.harmazing.protobuf.EventProtos.Event> getEventsList() {
        if (eventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(events_);
        } else {
          return eventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public int getEventsCount() {
        if (eventsBuilder_ == null) {
          return events_.size();
        } else {
          return eventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public com.harmazing.protobuf.EventProtos.Event getEvents(int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);
        } else {
          return eventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public Builder setEvents(
          int index, com.harmazing.protobuf.EventProtos.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.set(index, value);
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public Builder setEvents(
          int index, com.harmazing.protobuf.EventProtos.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public Builder addEvents(com.harmazing.protobuf.EventProtos.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public Builder addEvents(
          int index, com.harmazing.protobuf.EventProtos.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(index, value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public Builder addEvents(
          com.harmazing.protobuf.EventProtos.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public Builder addEvents(
          int index, com.harmazing.protobuf.EventProtos.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends com.harmazing.protobuf.EventProtos.Event> values) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          super.addAll(values, events_);
          onChanged();
        } else {
          eventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public Builder clearEvents() {
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public Builder removeEvents(int index) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.remove(index);
          onChanged();
        } else {
          eventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public com.harmazing.protobuf.EventProtos.Event.Builder getEventsBuilder(
          int index) {
        return getEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public com.harmazing.protobuf.EventProtos.EventOrBuilder getEventsOrBuilder(
          int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);  } else {
          return eventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public java.util.List<? extends com.harmazing.protobuf.EventProtos.EventOrBuilder> 
           getEventsOrBuilderList() {
        if (eventsBuilder_ != null) {
          return eventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(events_);
        }
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public com.harmazing.protobuf.EventProtos.Event.Builder addEventsBuilder() {
        return getEventsFieldBuilder().addBuilder(
            com.harmazing.protobuf.EventProtos.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public com.harmazing.protobuf.EventProtos.Event.Builder addEventsBuilder(
          int index) {
        return getEventsFieldBuilder().addBuilder(
            index, com.harmazing.protobuf.EventProtos.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Event events = 1;</code>
       */
      public java.util.List<com.harmazing.protobuf.EventProtos.Event.Builder> 
           getEventsBuilderList() {
        return getEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.harmazing.protobuf.EventProtos.Event, com.harmazing.protobuf.EventProtos.Event.Builder, com.harmazing.protobuf.EventProtos.EventOrBuilder> 
          getEventsFieldBuilder() {
        if (eventsBuilder_ == null) {
          eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.harmazing.protobuf.EventProtos.Event, com.harmazing.protobuf.EventProtos.Event.Builder, com.harmazing.protobuf.EventProtos.EventOrBuilder>(
                  events_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        return eventsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.EventReport)
    }

    static {
      defaultInstance = new EventReport(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.EventReport)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Event_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_EventReport_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_EventReport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022msgdef/event.proto\022\010protobuf\032\024msgdef/c" +
      "ommand.proto\"\341\005\n\005Event\022\016\n\006source\030\001 \002(\t\022\'" +
      "\n\004type\030\002 \002(\0162\031.protobuf.Event.EventType\022" +
      "\030\n\020string_parameter\030\003 \001(\t\022\025\n\rint_paramet" +
      "er\030\004 \001(\r\022\024\n\014ac_exception\030\005 \001(\014\022%\n\tir_pac" +
      "ket\030\006 \001(\0132\022.protobuf.IrPacket\022\"\n\005color\030\007" +
      " \001(\0132\023.protobuf.LampColor\"\214\004\n\tEventType\022" +
      "\017\n\013SENSOR_JOIN\020\000\022\020\n\014SENSOR_LEAVE\020\001\022\017\n\013SE" +
      "NSOR_PAIR\020\002\022\021\n\rSENSOR_UNPAIR\020\003\022\027\n\023SENSOR" +
      "_PAIR_REQUEST\020\004\022\026\n\022SENSOR_BATTERY_LOW\020\005\022",
      "\020\n\014SENSOR_AC_ON\020\006\022\021\n\rSENSOR_AC_OFF\020\007\022\032\n\026" +
      "SENSOR_AC_MODE_CHANGED\020\010\022\032\n\026SENSOR_AC_WI" +
      "ND_CHANGED\020\t\022 \n\034SENSOR_AC_LOCAL_TEMP_CHA" +
      "NGED\020\n\022!\n\035SENSOR_AC_TARGET_TEMP_CHANGED\020" +
      "\013\022\017\n\013SENSOR_OPEN\020\014\022\020\n\014SENSOR_CLOSE\020\r\022\027\n\023" +
      "SENSOR_AC_EXCEPTION\020\016\022\024\n\020IR_CODE_RECEIVE" +
      "D\020\017\022\020\n\014SENSOR_OO_ON\020\020\022\021\n\rSENSOR_OO_OFF\020\021" +
      "\022\026\n\022SENSOR_TEMPERATURE\020\022\022\023\n\017SENSOR_HUMID" +
      "ITY\020\023\022\025\n\021SENSOR_LAMP_COLOR\020\024\022\022\n\016SENSOR_A" +
      "LARMED\020\025\022\026\n\022SENSOR_NOT_ALARMED\020\026\".\n\013Even",
      "tReport\022\037\n\006events\030\001 \003(\0132\017.protobuf.Event" +
      "B%\n\026com.harmazing.protobufB\013EventProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Event_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Event_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Event_descriptor,
              new java.lang.String[] { "Source", "Type", "StringParameter", "IntParameter", "AcException", "IrPacket", "Color", });
          internal_static_protobuf_EventReport_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_EventReport_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_EventReport_descriptor,
              new java.lang.String[] { "Events", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.harmazing.protobuf.CommandProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
