// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgdef/gwinfo.proto

package com.harmazing.protobuf;

public final class GatewayInfoProtos {
  private GatewayInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GatewayInfoResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string EUI = 1;
    /**
     * <code>required string EUI = 1;</code>
     */
    boolean hasEUI();
    /**
     * <code>required string EUI = 1;</code>
     */
    java.lang.String getEUI();
    /**
     * <code>required string EUI = 1;</code>
     */
    com.google.protobuf.ByteString
        getEUIBytes();

    // required uint32 softwareVersion = 2;
    /**
     * <code>required uint32 softwareVersion = 2;</code>
     */
    boolean hasSoftwareVersion();
    /**
     * <code>required uint32 softwareVersion = 2;</code>
     */
    int getSoftwareVersion();

    // required uint32 hardwareVersion = 3;
    /**
     * <code>required uint32 hardwareVersion = 3;</code>
     */
    boolean hasHardwareVersion();
    /**
     * <code>required uint32 hardwareVersion = 3;</code>
     */
    int getHardwareVersion();

    // required int32 zigbeeChannel = 4;
    /**
     * <code>required int32 zigbeeChannel = 4;</code>
     */
    boolean hasZigbeeChannel();
    /**
     * <code>required int32 zigbeeChannel = 4;</code>
     */
    int getZigbeeChannel();

    // required int32 zigbeeChannelMask = 5;
    /**
     * <code>required int32 zigbeeChannelMask = 5;</code>
     */
    boolean hasZigbeeChannelMask();
    /**
     * <code>required int32 zigbeeChannelMask = 5;</code>
     */
    int getZigbeeChannelMask();

    // required int32 zigbeeTxPower = 6;
    /**
     * <code>required int32 zigbeeTxPower = 6;</code>
     */
    boolean hasZigbeeTxPower();
    /**
     * <code>required int32 zigbeeTxPower = 6;</code>
     */
    int getZigbeeTxPower();

    // repeated .protobuf.Sensor sensors = 7;
    /**
     * <code>repeated .protobuf.Sensor sensors = 7;</code>
     */
    java.util.List<com.harmazing.protobuf.SensorProtos.Sensor> 
        getSensorsList();
    /**
     * <code>repeated .protobuf.Sensor sensors = 7;</code>
     */
    com.harmazing.protobuf.SensorProtos.Sensor getSensors(int index);
    /**
     * <code>repeated .protobuf.Sensor sensors = 7;</code>
     */
    int getSensorsCount();
    /**
     * <code>repeated .protobuf.Sensor sensors = 7;</code>
     */
    java.util.List<? extends com.harmazing.protobuf.SensorProtos.SensorOrBuilder> 
        getSensorsOrBuilderList();
    /**
     * <code>repeated .protobuf.Sensor sensors = 7;</code>
     */
    com.harmazing.protobuf.SensorProtos.SensorOrBuilder getSensorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.GatewayInfoResponse}
   */
  public static final class GatewayInfoResponse extends
      com.google.protobuf.GeneratedMessage
      implements GatewayInfoResponseOrBuilder {
    // Use GatewayInfoResponse.newBuilder() to construct.
    private GatewayInfoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GatewayInfoResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GatewayInfoResponse defaultInstance;
    public static GatewayInfoResponse getDefaultInstance() {
      return defaultInstance;
    }

    public GatewayInfoResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GatewayInfoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              eUI_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              softwareVersion_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              hardwareVersion_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              zigbeeChannel_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              zigbeeChannelMask_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              zigbeeTxPower_ = input.readInt32();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                sensors_ = new java.util.ArrayList<com.harmazing.protobuf.SensorProtos.Sensor>();
                mutable_bitField0_ |= 0x00000040;
              }
              sensors_.add(input.readMessage(com.harmazing.protobuf.SensorProtos.Sensor.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          sensors_ = java.util.Collections.unmodifiableList(sensors_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.harmazing.protobuf.GatewayInfoProtos.internal_static_protobuf_GatewayInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.harmazing.protobuf.GatewayInfoProtos.internal_static_protobuf_GatewayInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse.class, com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<GatewayInfoResponse> PARSER =
        new com.google.protobuf.AbstractParser<GatewayInfoResponse>() {
      public GatewayInfoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GatewayInfoResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GatewayInfoResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string EUI = 1;
    public static final int EUI_FIELD_NUMBER = 1;
    private java.lang.Object eUI_;
    /**
     * <code>required string EUI = 1;</code>
     */
    public boolean hasEUI() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string EUI = 1;</code>
     */
    public java.lang.String getEUI() {
      java.lang.Object ref = eUI_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          eUI_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string EUI = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEUIBytes() {
      java.lang.Object ref = eUI_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eUI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 softwareVersion = 2;
    public static final int SOFTWAREVERSION_FIELD_NUMBER = 2;
    private int softwareVersion_;
    /**
     * <code>required uint32 softwareVersion = 2;</code>
     */
    public boolean hasSoftwareVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 softwareVersion = 2;</code>
     */
    public int getSoftwareVersion() {
      return softwareVersion_;
    }

    // required uint32 hardwareVersion = 3;
    public static final int HARDWAREVERSION_FIELD_NUMBER = 3;
    private int hardwareVersion_;
    /**
     * <code>required uint32 hardwareVersion = 3;</code>
     */
    public boolean hasHardwareVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 hardwareVersion = 3;</code>
     */
    public int getHardwareVersion() {
      return hardwareVersion_;
    }

    // required int32 zigbeeChannel = 4;
    public static final int ZIGBEECHANNEL_FIELD_NUMBER = 4;
    private int zigbeeChannel_;
    /**
     * <code>required int32 zigbeeChannel = 4;</code>
     */
    public boolean hasZigbeeChannel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 zigbeeChannel = 4;</code>
     */
    public int getZigbeeChannel() {
      return zigbeeChannel_;
    }

    // required int32 zigbeeChannelMask = 5;
    public static final int ZIGBEECHANNELMASK_FIELD_NUMBER = 5;
    private int zigbeeChannelMask_;
    /**
     * <code>required int32 zigbeeChannelMask = 5;</code>
     */
    public boolean hasZigbeeChannelMask() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 zigbeeChannelMask = 5;</code>
     */
    public int getZigbeeChannelMask() {
      return zigbeeChannelMask_;
    }

    // required int32 zigbeeTxPower = 6;
    public static final int ZIGBEETXPOWER_FIELD_NUMBER = 6;
    private int zigbeeTxPower_;
    /**
     * <code>required int32 zigbeeTxPower = 6;</code>
     */
    public boolean hasZigbeeTxPower() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 zigbeeTxPower = 6;</code>
     */
    public int getZigbeeTxPower() {
      return zigbeeTxPower_;
    }

    // repeated .protobuf.Sensor sensors = 7;
    public static final int SENSORS_FIELD_NUMBER = 7;
    private java.util.List<com.harmazing.protobuf.SensorProtos.Sensor> sensors_;
    /**
     * <code>repeated .protobuf.Sensor sensors = 7;</code>
     */
    public java.util.List<com.harmazing.protobuf.SensorProtos.Sensor> getSensorsList() {
      return sensors_;
    }
    /**
     * <code>repeated .protobuf.Sensor sensors = 7;</code>
     */
    public java.util.List<? extends com.harmazing.protobuf.SensorProtos.SensorOrBuilder> 
        getSensorsOrBuilderList() {
      return sensors_;
    }
    /**
     * <code>repeated .protobuf.Sensor sensors = 7;</code>
     */
    public int getSensorsCount() {
      return sensors_.size();
    }
    /**
     * <code>repeated .protobuf.Sensor sensors = 7;</code>
     */
    public com.harmazing.protobuf.SensorProtos.Sensor getSensors(int index) {
      return sensors_.get(index);
    }
    /**
     * <code>repeated .protobuf.Sensor sensors = 7;</code>
     */
    public com.harmazing.protobuf.SensorProtos.SensorOrBuilder getSensorsOrBuilder(
        int index) {
      return sensors_.get(index);
    }

    private void initFields() {
      eUI_ = "";
      softwareVersion_ = 0;
      hardwareVersion_ = 0;
      zigbeeChannel_ = 0;
      zigbeeChannelMask_ = 0;
      zigbeeTxPower_ = 0;
      sensors_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEUI()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSoftwareVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHardwareVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZigbeeChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZigbeeChannelMask()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZigbeeTxPower()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSensorsCount(); i++) {
        if (!getSensors(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEUIBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, softwareVersion_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, hardwareVersion_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, zigbeeChannel_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, zigbeeChannelMask_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, zigbeeTxPower_);
      }
      for (int i = 0; i < sensors_.size(); i++) {
        output.writeMessage(7, sensors_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEUIBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, softwareVersion_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, hardwareVersion_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, zigbeeChannel_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, zigbeeChannelMask_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, zigbeeTxPower_);
      }
      for (int i = 0; i < sensors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, sensors_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.GatewayInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.harmazing.protobuf.GatewayInfoProtos.internal_static_protobuf_GatewayInfoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.harmazing.protobuf.GatewayInfoProtos.internal_static_protobuf_GatewayInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse.class, com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse.Builder.class);
      }

      // Construct using com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSensorsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        eUI_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        softwareVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hardwareVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        zigbeeChannel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        zigbeeChannelMask_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        zigbeeTxPower_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (sensorsBuilder_ == null) {
          sensors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          sensorsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.harmazing.protobuf.GatewayInfoProtos.internal_static_protobuf_GatewayInfoResponse_descriptor;
      }

      public com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse getDefaultInstanceForType() {
        return com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse.getDefaultInstance();
      }

      public com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse build() {
        com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse buildPartial() {
        com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse result = new com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.eUI_ = eUI_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.softwareVersion_ = softwareVersion_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hardwareVersion_ = hardwareVersion_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.zigbeeChannel_ = zigbeeChannel_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.zigbeeChannelMask_ = zigbeeChannelMask_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.zigbeeTxPower_ = zigbeeTxPower_;
        if (sensorsBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            sensors_ = java.util.Collections.unmodifiableList(sensors_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.sensors_ = sensors_;
        } else {
          result.sensors_ = sensorsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse) {
          return mergeFrom((com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse other) {
        if (other == com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse.getDefaultInstance()) return this;
        if (other.hasEUI()) {
          bitField0_ |= 0x00000001;
          eUI_ = other.eUI_;
          onChanged();
        }
        if (other.hasSoftwareVersion()) {
          setSoftwareVersion(other.getSoftwareVersion());
        }
        if (other.hasHardwareVersion()) {
          setHardwareVersion(other.getHardwareVersion());
        }
        if (other.hasZigbeeChannel()) {
          setZigbeeChannel(other.getZigbeeChannel());
        }
        if (other.hasZigbeeChannelMask()) {
          setZigbeeChannelMask(other.getZigbeeChannelMask());
        }
        if (other.hasZigbeeTxPower()) {
          setZigbeeTxPower(other.getZigbeeTxPower());
        }
        if (sensorsBuilder_ == null) {
          if (!other.sensors_.isEmpty()) {
            if (sensors_.isEmpty()) {
              sensors_ = other.sensors_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureSensorsIsMutable();
              sensors_.addAll(other.sensors_);
            }
            onChanged();
          }
        } else {
          if (!other.sensors_.isEmpty()) {
            if (sensorsBuilder_.isEmpty()) {
              sensorsBuilder_.dispose();
              sensorsBuilder_ = null;
              sensors_ = other.sensors_;
              bitField0_ = (bitField0_ & ~0x00000040);
              sensorsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSensorsFieldBuilder() : null;
            } else {
              sensorsBuilder_.addAllMessages(other.sensors_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEUI()) {
          
          return false;
        }
        if (!hasSoftwareVersion()) {
          
          return false;
        }
        if (!hasHardwareVersion()) {
          
          return false;
        }
        if (!hasZigbeeChannel()) {
          
          return false;
        }
        if (!hasZigbeeChannelMask()) {
          
          return false;
        }
        if (!hasZigbeeTxPower()) {
          
          return false;
        }
        for (int i = 0; i < getSensorsCount(); i++) {
          if (!getSensors(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.harmazing.protobuf.GatewayInfoProtos.GatewayInfoResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string EUI = 1;
      private java.lang.Object eUI_ = "";
      /**
       * <code>required string EUI = 1;</code>
       */
      public boolean hasEUI() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string EUI = 1;</code>
       */
      public java.lang.String getEUI() {
        java.lang.Object ref = eUI_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          eUI_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string EUI = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEUIBytes() {
        java.lang.Object ref = eUI_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eUI_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string EUI = 1;</code>
       */
      public Builder setEUI(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        eUI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string EUI = 1;</code>
       */
      public Builder clearEUI() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eUI_ = getDefaultInstance().getEUI();
        onChanged();
        return this;
      }
      /**
       * <code>required string EUI = 1;</code>
       */
      public Builder setEUIBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        eUI_ = value;
        onChanged();
        return this;
      }

      // required uint32 softwareVersion = 2;
      private int softwareVersion_ ;
      /**
       * <code>required uint32 softwareVersion = 2;</code>
       */
      public boolean hasSoftwareVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 softwareVersion = 2;</code>
       */
      public int getSoftwareVersion() {
        return softwareVersion_;
      }
      /**
       * <code>required uint32 softwareVersion = 2;</code>
       */
      public Builder setSoftwareVersion(int value) {
        bitField0_ |= 0x00000002;
        softwareVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 softwareVersion = 2;</code>
       */
      public Builder clearSoftwareVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        softwareVersion_ = 0;
        onChanged();
        return this;
      }

      // required uint32 hardwareVersion = 3;
      private int hardwareVersion_ ;
      /**
       * <code>required uint32 hardwareVersion = 3;</code>
       */
      public boolean hasHardwareVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 hardwareVersion = 3;</code>
       */
      public int getHardwareVersion() {
        return hardwareVersion_;
      }
      /**
       * <code>required uint32 hardwareVersion = 3;</code>
       */
      public Builder setHardwareVersion(int value) {
        bitField0_ |= 0x00000004;
        hardwareVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 hardwareVersion = 3;</code>
       */
      public Builder clearHardwareVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hardwareVersion_ = 0;
        onChanged();
        return this;
      }

      // required int32 zigbeeChannel = 4;
      private int zigbeeChannel_ ;
      /**
       * <code>required int32 zigbeeChannel = 4;</code>
       */
      public boolean hasZigbeeChannel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 zigbeeChannel = 4;</code>
       */
      public int getZigbeeChannel() {
        return zigbeeChannel_;
      }
      /**
       * <code>required int32 zigbeeChannel = 4;</code>
       */
      public Builder setZigbeeChannel(int value) {
        bitField0_ |= 0x00000008;
        zigbeeChannel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 zigbeeChannel = 4;</code>
       */
      public Builder clearZigbeeChannel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        zigbeeChannel_ = 0;
        onChanged();
        return this;
      }

      // required int32 zigbeeChannelMask = 5;
      private int zigbeeChannelMask_ ;
      /**
       * <code>required int32 zigbeeChannelMask = 5;</code>
       */
      public boolean hasZigbeeChannelMask() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 zigbeeChannelMask = 5;</code>
       */
      public int getZigbeeChannelMask() {
        return zigbeeChannelMask_;
      }
      /**
       * <code>required int32 zigbeeChannelMask = 5;</code>
       */
      public Builder setZigbeeChannelMask(int value) {
        bitField0_ |= 0x00000010;
        zigbeeChannelMask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 zigbeeChannelMask = 5;</code>
       */
      public Builder clearZigbeeChannelMask() {
        bitField0_ = (bitField0_ & ~0x00000010);
        zigbeeChannelMask_ = 0;
        onChanged();
        return this;
      }

      // required int32 zigbeeTxPower = 6;
      private int zigbeeTxPower_ ;
      /**
       * <code>required int32 zigbeeTxPower = 6;</code>
       */
      public boolean hasZigbeeTxPower() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 zigbeeTxPower = 6;</code>
       */
      public int getZigbeeTxPower() {
        return zigbeeTxPower_;
      }
      /**
       * <code>required int32 zigbeeTxPower = 6;</code>
       */
      public Builder setZigbeeTxPower(int value) {
        bitField0_ |= 0x00000020;
        zigbeeTxPower_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 zigbeeTxPower = 6;</code>
       */
      public Builder clearZigbeeTxPower() {
        bitField0_ = (bitField0_ & ~0x00000020);
        zigbeeTxPower_ = 0;
        onChanged();
        return this;
      }

      // repeated .protobuf.Sensor sensors = 7;
      private java.util.List<com.harmazing.protobuf.SensorProtos.Sensor> sensors_ =
        java.util.Collections.emptyList();
      private void ensureSensorsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          sensors_ = new java.util.ArrayList<com.harmazing.protobuf.SensorProtos.Sensor>(sensors_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.harmazing.protobuf.SensorProtos.Sensor, com.harmazing.protobuf.SensorProtos.Sensor.Builder, com.harmazing.protobuf.SensorProtos.SensorOrBuilder> sensorsBuilder_;

      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public java.util.List<com.harmazing.protobuf.SensorProtos.Sensor> getSensorsList() {
        if (sensorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sensors_);
        } else {
          return sensorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public int getSensorsCount() {
        if (sensorsBuilder_ == null) {
          return sensors_.size();
        } else {
          return sensorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public com.harmazing.protobuf.SensorProtos.Sensor getSensors(int index) {
        if (sensorsBuilder_ == null) {
          return sensors_.get(index);
        } else {
          return sensorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public Builder setSensors(
          int index, com.harmazing.protobuf.SensorProtos.Sensor value) {
        if (sensorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorsIsMutable();
          sensors_.set(index, value);
          onChanged();
        } else {
          sensorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public Builder setSensors(
          int index, com.harmazing.protobuf.SensorProtos.Sensor.Builder builderForValue) {
        if (sensorsBuilder_ == null) {
          ensureSensorsIsMutable();
          sensors_.set(index, builderForValue.build());
          onChanged();
        } else {
          sensorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public Builder addSensors(com.harmazing.protobuf.SensorProtos.Sensor value) {
        if (sensorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorsIsMutable();
          sensors_.add(value);
          onChanged();
        } else {
          sensorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public Builder addSensors(
          int index, com.harmazing.protobuf.SensorProtos.Sensor value) {
        if (sensorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorsIsMutable();
          sensors_.add(index, value);
          onChanged();
        } else {
          sensorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public Builder addSensors(
          com.harmazing.protobuf.SensorProtos.Sensor.Builder builderForValue) {
        if (sensorsBuilder_ == null) {
          ensureSensorsIsMutable();
          sensors_.add(builderForValue.build());
          onChanged();
        } else {
          sensorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public Builder addSensors(
          int index, com.harmazing.protobuf.SensorProtos.Sensor.Builder builderForValue) {
        if (sensorsBuilder_ == null) {
          ensureSensorsIsMutable();
          sensors_.add(index, builderForValue.build());
          onChanged();
        } else {
          sensorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public Builder addAllSensors(
          java.lang.Iterable<? extends com.harmazing.protobuf.SensorProtos.Sensor> values) {
        if (sensorsBuilder_ == null) {
          ensureSensorsIsMutable();
          super.addAll(values, sensors_);
          onChanged();
        } else {
          sensorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public Builder clearSensors() {
        if (sensorsBuilder_ == null) {
          sensors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          sensorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public Builder removeSensors(int index) {
        if (sensorsBuilder_ == null) {
          ensureSensorsIsMutable();
          sensors_.remove(index);
          onChanged();
        } else {
          sensorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public com.harmazing.protobuf.SensorProtos.Sensor.Builder getSensorsBuilder(
          int index) {
        return getSensorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public com.harmazing.protobuf.SensorProtos.SensorOrBuilder getSensorsOrBuilder(
          int index) {
        if (sensorsBuilder_ == null) {
          return sensors_.get(index);  } else {
          return sensorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public java.util.List<? extends com.harmazing.protobuf.SensorProtos.SensorOrBuilder> 
           getSensorsOrBuilderList() {
        if (sensorsBuilder_ != null) {
          return sensorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sensors_);
        }
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public com.harmazing.protobuf.SensorProtos.Sensor.Builder addSensorsBuilder() {
        return getSensorsFieldBuilder().addBuilder(
            com.harmazing.protobuf.SensorProtos.Sensor.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public com.harmazing.protobuf.SensorProtos.Sensor.Builder addSensorsBuilder(
          int index) {
        return getSensorsFieldBuilder().addBuilder(
            index, com.harmazing.protobuf.SensorProtos.Sensor.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Sensor sensors = 7;</code>
       */
      public java.util.List<com.harmazing.protobuf.SensorProtos.Sensor.Builder> 
           getSensorsBuilderList() {
        return getSensorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.harmazing.protobuf.SensorProtos.Sensor, com.harmazing.protobuf.SensorProtos.Sensor.Builder, com.harmazing.protobuf.SensorProtos.SensorOrBuilder> 
          getSensorsFieldBuilder() {
        if (sensorsBuilder_ == null) {
          sensorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.harmazing.protobuf.SensorProtos.Sensor, com.harmazing.protobuf.SensorProtos.Sensor.Builder, com.harmazing.protobuf.SensorProtos.SensorOrBuilder>(
                  sensors_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          sensors_ = null;
        }
        return sensorsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.GatewayInfoResponse)
    }

    static {
      defaultInstance = new GatewayInfoResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.GatewayInfoResponse)
  }

  public interface HeartbeatResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protobuf.HeartbeatResponse}
   */
  public static final class HeartbeatResponse extends
      com.google.protobuf.GeneratedMessage
      implements HeartbeatResponseOrBuilder {
    // Use HeartbeatResponse.newBuilder() to construct.
    private HeartbeatResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartbeatResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartbeatResponse defaultInstance;
    public static HeartbeatResponse getDefaultInstance() {
      return defaultInstance;
    }

    public HeartbeatResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartbeatResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.harmazing.protobuf.GatewayInfoProtos.internal_static_protobuf_HeartbeatResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.harmazing.protobuf.GatewayInfoProtos.internal_static_protobuf_HeartbeatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse.class, com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartbeatResponse> PARSER =
        new com.google.protobuf.AbstractParser<HeartbeatResponse>() {
      public HeartbeatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartbeatResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartbeatResponse> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.HeartbeatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.harmazing.protobuf.GatewayInfoProtos.internal_static_protobuf_HeartbeatResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.harmazing.protobuf.GatewayInfoProtos.internal_static_protobuf_HeartbeatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse.class, com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse.Builder.class);
      }

      // Construct using com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.harmazing.protobuf.GatewayInfoProtos.internal_static_protobuf_HeartbeatResponse_descriptor;
      }

      public com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse getDefaultInstanceForType() {
        return com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse.getDefaultInstance();
      }

      public com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse build() {
        com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse buildPartial() {
        com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse result = new com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse) {
          return mergeFrom((com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse other) {
        if (other == com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.harmazing.protobuf.GatewayInfoProtos.HeartbeatResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.HeartbeatResponse)
    }

    static {
      defaultInstance = new HeartbeatResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.HeartbeatResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_GatewayInfoResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_GatewayInfoResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_HeartbeatResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_HeartbeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023msgdef/gwinfo.proto\022\010protobuf\032\023msgdef/" +
      "sensor.proto\"\300\001\n\023GatewayInfoResponse\022\013\n\003" +
      "EUI\030\001 \002(\t\022\027\n\017softwareVersion\030\002 \002(\r\022\027\n\017ha" +
      "rdwareVersion\030\003 \002(\r\022\025\n\rzigbeeChannel\030\004 \002" +
      "(\005\022\031\n\021zigbeeChannelMask\030\005 \002(\005\022\025\n\rzigbeeT" +
      "xPower\030\006 \002(\005\022!\n\007sensors\030\007 \003(\0132\020.protobuf" +
      ".Sensor\"\023\n\021HeartbeatResponseB+\n\026com.harm" +
      "azing.protobufB\021GatewayInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_GatewayInfoResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_GatewayInfoResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_GatewayInfoResponse_descriptor,
              new java.lang.String[] { "EUI", "SoftwareVersion", "HardwareVersion", "ZigbeeChannel", "ZigbeeChannelMask", "ZigbeeTxPower", "Sensors", });
          internal_static_protobuf_HeartbeatResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_HeartbeatResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_HeartbeatResponse_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.harmazing.protobuf.SensorProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
